//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonicRetro.SonLVL.Properties {
	using System;
    
    
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {
        
		private static global::System.Resources.ResourceManager resourceMan;
        
		private static global::System.Globalization.CultureInfo resourceCulture;
        
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}
        
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SonicRetro.SonLVL.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
        
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
        
		internal static System.Drawing.Icon clockmon {
			get {
				object obj = ResourceManager.GetObject("clockmon", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
        
		internal static System.Drawing.Bitmap copy {
			get {
				object obj = ResourceManager.GetObject("copy", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
        
		internal static System.Drawing.Bitmap cut {
			get {
				object obj = ResourceManager.GetObject("cut", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
        
		internal static System.Drawing.Bitmap delete {
			get {
				object obj = ResourceManager.GetObject("delete", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
        
		internal static System.Drawing.Icon gogglemon {
			get {
				object obj = ResourceManager.GetObject("gogglemon", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
        
		internal static System.Drawing.Icon lightningmon {
			get {
				object obj = ResourceManager.GetObject("lightningmon", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
        
		internal static System.Drawing.Bitmap mon {
			get {
				object obj = ResourceManager.GetObject("mon", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
        
		internal static System.Drawing.Bitmap paste {
			get {
				object obj = ResourceManager.GetObject("paste", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
        
		internal static byte[] pencilcur {
			get {
				object obj = ResourceManager.GetObject("pencilcur", resourceCulture);
				return ((byte[])(obj));
			}
		}
        
		internal static System.Drawing.Icon ringmon1 {
			get {
				object obj = ResourceManager.GetObject("ringmon1", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
        
		internal static System.Drawing.Bitmap rng {
			get {
				object obj = ResourceManager.GetObject("rng", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
        
		internal static System.Drawing.Bitmap sonicbored1 {
			get {
				object obj = ResourceManager.GetObject("sonicbored1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
        
		internal static System.Drawing.Bitmap sonicbored2 {
			get {
				object obj = ResourceManager.GetObject("sonicbored2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
        
		internal static System.Drawing.Icon Tailsmon2 {
			get {
				object obj = ResourceManager.GetObject("Tailsmon2", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
        
		internal static System.Drawing.Bitmap UnknownImg {
			get {
				object obj = ResourceManager.GetObject("UnknownImg", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
        
		internal static System.Drawing.Bitmap UnknownImg3K {
			get {
				object obj = ResourceManager.GetObject("UnknownImg3K", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
        
		internal static System.Drawing.Icon watermon {
			get {
				object obj = ResourceManager.GetObject("watermon", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
	}
}
